### ISSUE TITLE
Missing Header

### ISSUE THREAD

**Issue by JoergFF** [Debianguru/MailWebsiteChanges#11]
Hello,

I forward this bug from Debian[1]:

[quote]
Dear Maintainer,

Usually this application works well, but fails to fetch the following
site:

    {
     'shortname': 'WMO Library',
     'type': 'html',
     'uri': 'https://library.wmo.int/opac/index.php?lvl=infopages&lang=en_UK&pagesid=1',
     'contentxpath': '//*[@id="overview"]/tbody/tr[1]/td[1]',
     'encoding': 'utf-8'
    }

with

    {'warning': 'WARNING: could not open URL; maybe content was moved?\n\nHTTP Error 403: Forbidden', 'titles': None, 'content': None}

Best regards,
Manolo Díaz
[/quote]

I have found that the site requests the header Accept.

CU
Jörg

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862004

**Comment by Debianguru** [comment]
this is fixed in the latest release, thank you!
